/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.DPBuilding();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DPBuilding', function() {
    it('should create an instance of DPBuilding', function() {
      // uncomment below and update the code to test DPBuilding
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be.a(DirectPortalRestApi.DPBuilding);
    });

    it('should have the property complexId (base name: "ComplexId")', function() {
      // uncomment below and update the code to test the property complexId
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property complex (base name: "Complex")', function() {
      // uncomment below and update the code to test the property complex
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property units (base name: "Units")', function() {
      // uncomment below and update the code to test the property units
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "Features")', function() {
      // uncomment below and update the code to test the property features
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property contractDetails (base name: "ContractDetails")', function() {
      // uncomment below and update the code to test the property contractDetails
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property floors (base name: "Floors")', function() {
      // uncomment below and update the code to test the property floors
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property constructionStartDate (base name: "ConstructionStartDate")', function() {
      // uncomment below and update the code to test the property constructionStartDate
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property constructionEndDate (base name: "ConstructionEndDate")', function() {
      // uncomment below and update the code to test the property constructionEndDate
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property tagline (base name: "Tagline")', function() {
      // uncomment below and update the code to test the property tagline
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "Kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property termsAndConditions (base name: "TermsAndConditions")', function() {
      // uncomment below and update the code to test the property termsAndConditions
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property floorHeight (base name: "FloorHeight")', function() {
      // uncomment below and update the code to test the property floorHeight
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property contactDetails (base name: "ContactDetails")', function() {
      // uncomment below and update the code to test the property contactDetails
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property statusType (base name: "StatusType")', function() {
      // uncomment below and update the code to test the property statusType
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property translations (base name: "Translations")', function() {
      // uncomment below and update the code to test the property translations
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property relationships (base name: "Relationships")', function() {
      // uncomment below and update the code to test the property relationships
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "Longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "Latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property shape (base name: "Shape")', function() {
      // uncomment below and update the code to test the property shape
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property coordinates (base name: "Coordinates")', function() {
      // uncomment below and update the code to test the property coordinates
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property shapeColor (base name: "ShapeColor")', function() {
      // uncomment below and update the code to test the property shapeColor
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "Active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property _default (base name: "Default")', function() {
      // uncomment below and update the code to test the property _default
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property migrationID (base name: "MigrationID")', function() {
      // uncomment below and update the code to test the property migrationID
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "Color")', function() {
      // uncomment below and update the code to test the property color
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionID (base name: "SubscriptionID")', function() {
      // uncomment below and update the code to test the property subscriptionID
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

    it('should have the property subscription (base name: "Subscription")', function() {
      // uncomment below and update the code to test the property subscription
      //var instane = new DirectPortalRestApi.DPBuilding();
      //expect(instance).to.be();
    });

  });

}));
