/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.DocumentTypeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentTypeApi', function() {
    describe('apiDocumentTypeActivateByIdGet', function() {
      it('should call apiDocumentTypeActivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeActivateByIdGet
        //instance.apiDocumentTypeActivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeActiveGet', function() {
      it('should call apiDocumentTypeActiveGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeActiveGet
        //instance.apiDocumentTypeActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeByIdGet', function() {
      it('should call apiDocumentTypeByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeByIdGet
        //instance.apiDocumentTypeByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeByNameByIdGet', function() {
      it('should call apiDocumentTypeByNameByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeByNameByIdGet
        //instance.apiDocumentTypeByNameByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeByNamePost', function() {
      it('should call apiDocumentTypeByNamePost successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeByNamePost
        //instance.apiDocumentTypeByNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeContactAddressesByIdGet', function() {
      it('should call apiDocumentTypeContactAddressesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeContactAddressesByIdGet
        //instance.apiDocumentTypeContactAddressesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeContactAddressesByIdPost', function() {
      it('should call apiDocumentTypeContactAddressesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeContactAddressesByIdPost
        //instance.apiDocumentTypeContactAddressesByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeContactDetailsByIdGet', function() {
      it('should call apiDocumentTypeContactDetailsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeContactDetailsByIdGet
        //instance.apiDocumentTypeContactDetailsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeContactDetailsByIdPost', function() {
      it('should call apiDocumentTypeContactDetailsByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeContactDetailsByIdPost
        //instance.apiDocumentTypeContactDetailsByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeDeactivateByIdGet', function() {
      it('should call apiDocumentTypeDeactivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeDeactivateByIdGet
        //instance.apiDocumentTypeDeactivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeGet', function() {
      it('should call apiDocumentTypeGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeGet
        //instance.apiDocumentTypeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeNotesByIdGet', function() {
      it('should call apiDocumentTypeNotesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeNotesByIdGet
        //instance.apiDocumentTypeNotesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypePost', function() {
      it('should call apiDocumentTypePost successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypePost
        //instance.apiDocumentTypePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypePut', function() {
      it('should call apiDocumentTypePut successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypePut
        //instance.apiDocumentTypePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeRelationshipsByIdGet', function() {
      it('should call apiDocumentTypeRelationshipsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeRelationshipsByIdGet
        //instance.apiDocumentTypeRelationshipsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeSetAsDefaultByIdGet', function() {
      it('should call apiDocumentTypeSetAsDefaultByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeSetAsDefaultByIdGet
        //instance.apiDocumentTypeSetAsDefaultByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDocumentTypeTranslationsByIdGet', function() {
      it('should call apiDocumentTypeTranslationsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiDocumentTypeTranslationsByIdGet
        //instance.apiDocumentTypeTranslationsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
