/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.OrganizationUnitStatusApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationUnitStatusApi', function() {
    describe('apiOrganizationUnitStatusActivateByIdGet', function() {
      it('should call apiOrganizationUnitStatusActivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusActivateByIdGet
        //instance.apiOrganizationUnitStatusActivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusActiveGet', function() {
      it('should call apiOrganizationUnitStatusActiveGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusActiveGet
        //instance.apiOrganizationUnitStatusActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusByIdGet', function() {
      it('should call apiOrganizationUnitStatusByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusByIdGet
        //instance.apiOrganizationUnitStatusByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusByNameByIdGet', function() {
      it('should call apiOrganizationUnitStatusByNameByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusByNameByIdGet
        //instance.apiOrganizationUnitStatusByNameByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusByNamePost', function() {
      it('should call apiOrganizationUnitStatusByNamePost successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusByNamePost
        //instance.apiOrganizationUnitStatusByNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusContactAddressesByIdGet', function() {
      it('should call apiOrganizationUnitStatusContactAddressesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusContactAddressesByIdGet
        //instance.apiOrganizationUnitStatusContactAddressesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusContactAddressesByIdPost', function() {
      it('should call apiOrganizationUnitStatusContactAddressesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusContactAddressesByIdPost
        //instance.apiOrganizationUnitStatusContactAddressesByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusContactDetailsByIdGet', function() {
      it('should call apiOrganizationUnitStatusContactDetailsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusContactDetailsByIdGet
        //instance.apiOrganizationUnitStatusContactDetailsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusContactDetailsByIdPost', function() {
      it('should call apiOrganizationUnitStatusContactDetailsByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusContactDetailsByIdPost
        //instance.apiOrganizationUnitStatusContactDetailsByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusDeactivateByIdGet', function() {
      it('should call apiOrganizationUnitStatusDeactivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusDeactivateByIdGet
        //instance.apiOrganizationUnitStatusDeactivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusGet', function() {
      it('should call apiOrganizationUnitStatusGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusGet
        //instance.apiOrganizationUnitStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusNotesByIdGet', function() {
      it('should call apiOrganizationUnitStatusNotesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusNotesByIdGet
        //instance.apiOrganizationUnitStatusNotesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusPost', function() {
      it('should call apiOrganizationUnitStatusPost successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusPost
        //instance.apiOrganizationUnitStatusPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusPut', function() {
      it('should call apiOrganizationUnitStatusPut successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusPut
        //instance.apiOrganizationUnitStatusPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusRelationshipsByIdGet', function() {
      it('should call apiOrganizationUnitStatusRelationshipsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusRelationshipsByIdGet
        //instance.apiOrganizationUnitStatusRelationshipsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusSetAsDefaultByIdGet', function() {
      it('should call apiOrganizationUnitStatusSetAsDefaultByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusSetAsDefaultByIdGet
        //instance.apiOrganizationUnitStatusSetAsDefaultByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrganizationUnitStatusTranslationsByIdGet', function() {
      it('should call apiOrganizationUnitStatusTranslationsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrganizationUnitStatusTranslationsByIdGet
        //instance.apiOrganizationUnitStatusTranslationsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
