/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.PersonPrefixApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonPrefixApi', function() {
    describe('apiPersonPrefixActivateByIdGet', function() {
      it('should call apiPersonPrefixActivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixActivateByIdGet
        //instance.apiPersonPrefixActivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixActiveGet', function() {
      it('should call apiPersonPrefixActiveGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixActiveGet
        //instance.apiPersonPrefixActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixByIdGet', function() {
      it('should call apiPersonPrefixByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixByIdGet
        //instance.apiPersonPrefixByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixByNameByIdGet', function() {
      it('should call apiPersonPrefixByNameByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixByNameByIdGet
        //instance.apiPersonPrefixByNameByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixByNamePost', function() {
      it('should call apiPersonPrefixByNamePost successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixByNamePost
        //instance.apiPersonPrefixByNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixContactAddressesByIdGet', function() {
      it('should call apiPersonPrefixContactAddressesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixContactAddressesByIdGet
        //instance.apiPersonPrefixContactAddressesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixContactAddressesByIdPost', function() {
      it('should call apiPersonPrefixContactAddressesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixContactAddressesByIdPost
        //instance.apiPersonPrefixContactAddressesByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixContactDetailsByIdGet', function() {
      it('should call apiPersonPrefixContactDetailsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixContactDetailsByIdGet
        //instance.apiPersonPrefixContactDetailsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixContactDetailsByIdPost', function() {
      it('should call apiPersonPrefixContactDetailsByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixContactDetailsByIdPost
        //instance.apiPersonPrefixContactDetailsByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixDeactivateByIdGet', function() {
      it('should call apiPersonPrefixDeactivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixDeactivateByIdGet
        //instance.apiPersonPrefixDeactivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixGet', function() {
      it('should call apiPersonPrefixGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixGet
        //instance.apiPersonPrefixGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixNotesByIdGet', function() {
      it('should call apiPersonPrefixNotesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixNotesByIdGet
        //instance.apiPersonPrefixNotesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixPost', function() {
      it('should call apiPersonPrefixPost successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixPost
        //instance.apiPersonPrefixPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixPut', function() {
      it('should call apiPersonPrefixPut successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixPut
        //instance.apiPersonPrefixPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixRelationshipsByIdGet', function() {
      it('should call apiPersonPrefixRelationshipsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixRelationshipsByIdGet
        //instance.apiPersonPrefixRelationshipsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixSetAsDefaultByIdGet', function() {
      it('should call apiPersonPrefixSetAsDefaultByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixSetAsDefaultByIdGet
        //instance.apiPersonPrefixSetAsDefaultByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPersonPrefixTranslationsByIdGet', function() {
      it('should call apiPersonPrefixTranslationsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiPersonPrefixTranslationsByIdGet
        //instance.apiPersonPrefixTranslationsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
