/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.QuotaApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuotaApi', function() {
    describe('apiQuotaActivateByIdGet', function() {
      it('should call apiQuotaActivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaActivateByIdGet
        //instance.apiQuotaActivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaActiveGet', function() {
      it('should call apiQuotaActiveGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaActiveGet
        //instance.apiQuotaActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaByIdGet', function() {
      it('should call apiQuotaByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaByIdGet
        //instance.apiQuotaByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaByNameByIdGet', function() {
      it('should call apiQuotaByNameByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaByNameByIdGet
        //instance.apiQuotaByNameByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaByNamePost', function() {
      it('should call apiQuotaByNamePost successfully', function(done) {
        //uncomment below and update the code to test apiQuotaByNamePost
        //instance.apiQuotaByNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaContactAddressesByIdGet', function() {
      it('should call apiQuotaContactAddressesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaContactAddressesByIdGet
        //instance.apiQuotaContactAddressesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaContactAddressesByIdPost', function() {
      it('should call apiQuotaContactAddressesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiQuotaContactAddressesByIdPost
        //instance.apiQuotaContactAddressesByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaContactDetailsByIdGet', function() {
      it('should call apiQuotaContactDetailsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaContactDetailsByIdGet
        //instance.apiQuotaContactDetailsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaContactDetailsByIdPost', function() {
      it('should call apiQuotaContactDetailsByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiQuotaContactDetailsByIdPost
        //instance.apiQuotaContactDetailsByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaDeactivateByIdGet', function() {
      it('should call apiQuotaDeactivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaDeactivateByIdGet
        //instance.apiQuotaDeactivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaGet', function() {
      it('should call apiQuotaGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaGet
        //instance.apiQuotaGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaNotesByIdGet', function() {
      it('should call apiQuotaNotesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaNotesByIdGet
        //instance.apiQuotaNotesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaPost', function() {
      it('should call apiQuotaPost successfully', function(done) {
        //uncomment below and update the code to test apiQuotaPost
        //instance.apiQuotaPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaPut', function() {
      it('should call apiQuotaPut successfully', function(done) {
        //uncomment below and update the code to test apiQuotaPut
        //instance.apiQuotaPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaRelationshipsByIdGet', function() {
      it('should call apiQuotaRelationshipsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaRelationshipsByIdGet
        //instance.apiQuotaRelationshipsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaSetAsDefaultByIdGet', function() {
      it('should call apiQuotaSetAsDefaultByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaSetAsDefaultByIdGet
        //instance.apiQuotaSetAsDefaultByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiQuotaTranslationsByIdGet', function() {
      it('should call apiQuotaTranslationsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiQuotaTranslationsByIdGet
        //instance.apiQuotaTranslationsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
