/**
 * Direct Portal REST API
 * The Direct Portal REST API
 *
 * OpenAPI spec version: v1
 * Contact: info@direct-portal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DirectPortalRestApi);
  }
}(this, function(expect, DirectPortalRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DirectPortalRestApi.ReservationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReservationApi', function() {
    describe('apiReservationActivateByIdGet', function() {
      it('should call apiReservationActivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationActivateByIdGet
        //instance.apiReservationActivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationActiveGet', function() {
      it('should call apiReservationActiveGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationActiveGet
        //instance.apiReservationActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationByIdGet', function() {
      it('should call apiReservationByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationByIdGet
        //instance.apiReservationByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationByNameByIdGet', function() {
      it('should call apiReservationByNameByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationByNameByIdGet
        //instance.apiReservationByNameByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationByNamePost', function() {
      it('should call apiReservationByNamePost successfully', function(done) {
        //uncomment below and update the code to test apiReservationByNamePost
        //instance.apiReservationByNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationContactAddressesByIdGet', function() {
      it('should call apiReservationContactAddressesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationContactAddressesByIdGet
        //instance.apiReservationContactAddressesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationContactAddressesByIdPost', function() {
      it('should call apiReservationContactAddressesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiReservationContactAddressesByIdPost
        //instance.apiReservationContactAddressesByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationContactDetailsByIdGet', function() {
      it('should call apiReservationContactDetailsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationContactDetailsByIdGet
        //instance.apiReservationContactDetailsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationContactDetailsByIdPost', function() {
      it('should call apiReservationContactDetailsByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiReservationContactDetailsByIdPost
        //instance.apiReservationContactDetailsByIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationDeactivateByIdGet', function() {
      it('should call apiReservationDeactivateByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationDeactivateByIdGet
        //instance.apiReservationDeactivateByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationGet', function() {
      it('should call apiReservationGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationGet
        //instance.apiReservationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationNotesByIdGet', function() {
      it('should call apiReservationNotesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationNotesByIdGet
        //instance.apiReservationNotesByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationPost', function() {
      it('should call apiReservationPost successfully', function(done) {
        //uncomment below and update the code to test apiReservationPost
        //instance.apiReservationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationPut', function() {
      it('should call apiReservationPut successfully', function(done) {
        //uncomment below and update the code to test apiReservationPut
        //instance.apiReservationPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationRelationshipsByIdGet', function() {
      it('should call apiReservationRelationshipsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationRelationshipsByIdGet
        //instance.apiReservationRelationshipsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationSetAsDefaultByIdGet', function() {
      it('should call apiReservationSetAsDefaultByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationSetAsDefaultByIdGet
        //instance.apiReservationSetAsDefaultByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiReservationTranslationsByIdGet', function() {
      it('should call apiReservationTranslationsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiReservationTranslationsByIdGet
        //instance.apiReservationTranslationsByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
